trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: First
  jobs:
  - job: FirstJob
    steps:
      - bash: echo BuildJob
      - bash: $(PipelineLevelVariable)
      - bash: $(Build.BuildNumber)
      - bash: $(Build.BuildId)
      - bash: $(Build.SourceBranchName)
      - bash: $(Build.SourcesDirectory)
      - bash: $(System.DefaultWorkingDirectory)
      - bash: ls -R $(System.DefaultWorkingDirectory)
      - bash: $(Build.ArtifactStagingDirectory)
# - stage: DevDeploy
#   variables:
#     environment: Dev
#   dependsOn: Build
#   jobs:
#   - job: DevDeployJob
#     steps:
#       - bash: echo $(environment)DeployJob
# - stage: QADeploy
#   variables:
#     environment: QA
#   dependsOn: Build
#   jobs:
#   - job: QADeployJob
#     steps:
#       - bash: echo $(environment)DeployJob
# - stage: ProdDeploy
#   dependsOn: 
#   - DevDeploy
#   - QADeploy
#   jobs:
#   - job: ProdDeployJob
#     steps:
#       - bash: echo ProdDeployJob