trigger:
- main

strategy:
  matrix:
    linux:
      operatingSystem: 'ubuntu-latest'
    mac:
      operatingSystem: 'macos-latest'
pool:
  vmImage: $(operatingSystem)

steps:
- script: echo Running on $(operating system)
  displayName: 'Run a one line script'

