trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo K8s Terraform Azure!
  displayName: 'Run a one-line script'
- task: DownloadSecureFile@1
  name: publickey
  inputs:
    secureFile: 'azure_rsa.pub'
- task: TerraformCLI@2
  inputs:
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/configuration/iaac/azure/kubernetes'
    commandOptions: '-var client_id =$(client_id) -var client_secret=$(client_secret) -var ssh_public_key=$(publickey.secureFile)'
    backendType: 'azurerm'
    backendServiceArm: 'azure-resource-manager-connection-service'
    ensureBackend: true
    backendAzureRmResourceGroupName: 'terraform-azure-rg'
    backendAzureRmResourceGroupLocation: 'westeurope'
    backendAzureRmStorageAccountName: 'storageacctkartikeya'
    backendAzureRmContainerName: 'storageacctkarikeyacontainer'
    backendAzureRmKey: 'kubernetes-dev.tfstate'
    allowTelemetryCollection: true

- task: TerraformCLI@0
  inputs:
    command: 'apply'
    workingDirectory: '$(System.DefaultWorkingDirectory)/configuration/iaac/azure/kubernetes'
    commandOptions: '-var client_id =$(client_id) -var client_secret=$(client_secret) -var ssh_public_key=$(publickey.secureFile)'
    backendServiceArm: 'azure-resource-manager-connection-service'

- task: TerraformCLI@0
  inputs:
    command: 'destroy'
    workingDirectory: '$(System.DefaultWorkingDirectory)/configuration/iaac/azure/kubernetes'
    backendServiceArm: 'azure-resource-manager-connection-service'