trigger:
- main

resources:
- repo: self

variables:
  tag: 23 #'$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    # - task: Docker@2
    #   displayName: Build an image
    #   inputs:
    #     containerRegistry: 'kartikeya-docker-hub'
    #     repository: 'kartikeya123456/currency-exchange-devops'
    #     command: 'buildAndPush'
    #     Dockerfile: '**/Dockerfile'
    #     tags: '$(tag)'
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'manifests'
        publishLocation: 'Container'
        MaxArtifactSize: 100
- stage: Deploy
  displayName: Deploy image
  jobs:
  - job: Deploy
    displayName: Deploy
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)'
        Contents: '**/*.yaml'
        TargetFolder: '$(System.ArtifactsDirectory)'
    - task: DownloadPipelineArtifact@2
      inputs:
        buildType: 'current'
        artifactName: 'manifests'
        itemPattern: '**/*.yaml'
        targetPath: '$(System.ArtifactsDirectory)'
    
    - task: KubernetesManifest@0
      inputs:
        action: deploy
        kubernetesServiceConnection: 'azure-kubernetes-connection'
        namespace:  'default'
        manifests:  '$(System.ArtifactsDirectory)/configuration/kubernetes/deployment.yaml'
        containers:  'in28min/currency-exchange-devops:$(tag)'

